### ISSUE TITLE
Lightning NFC

### ISSUE THREAD

**Issue by dadofsambonzuki** [teambtcmap/btcmap-android#18]
Consider processing the `payment:lightningnfc ` tag and displaying them as contactless in the app.

I have updated the [Bitcoin page](https://wiki.openstreetmap.org/wiki/Bitcoin) on the OSM wiki with the payment tag info.

**Comment by bubelov** [comment]
How is that different from normal LN payments? I never tried that, would I be able to pay NFC merchant if I don't have NFC? Is there always a fallback to vanilla LN payments?

**Comment by dadofsambonzuki** [comment]
You could only pay using lightningnfc if you and the merchant had that. An
increasing amount of wallets support it (VoltPay, Breeze, BTCPay Server,
LNBits). There are also the Bolt Cards from CoinCorner and non-custodial
options to connect a lightning 'debit' card to your own node.

Definitely worthy of a separate method tag

Nathan Day

e: ***@***.***
m: +44 7982 234 581

**Comment by dadofsambonzuki** [comment]
You could only pay using lightningnfc if you and the merchant had that. An
increasing amount of wallets support it (VoltPay, Breeze, BTCPay Server,
LNBits). There are also the Bolt Cards from CoinCorner and non-custodial
options to connect a lightning 'debit' card to your own node.

Definitely worthy of a separate method tag

**Comment by secondl1ght** [comment]
This looks stale and has been added so closing.
