### ISSUE TITLE
Add Payment Type Filters

### ISSUE THREAD

**Issue by dadofsambonzuki** [teambtcmap/btcmap-android#19]
It would be cool to be able to filter my payment type. e.g. Onchain, Lightning, Lightning NFC.

**Comment by bubelov** [comment]
Definitely, as soon as this information becomes widely available. Currently, there is nothing to filter. I'd say 500 LN/NFC-enabled places is a fair threshold.

**Comment by secondl1ght** [comment]
Duplicate of https://github.com/teambtcmap/btcmap.org/issues/20

**Comment by dadofsambonzuki** [comment]
Not a dupe. This is for Android.
