### ISSUE TITLE
Filter by Vendor Type

### ISSUE THREAD

**Issue by dadofsambonzuki** [teambtcmap/btcmap-android#20]
It would be cool to be able to filter my type of vendor. e.g cafe, hairdresser, etc.

**Comment by bubelov** [comment]
There aren't that many places to justify filters, but it will be necessary if the number of places will grow.

Here are some interesting stats: https://github.com/bubelov/btcmap-android/blob/master/app/src/main/kotlin/icons/ElementExtensions.kt

We can pick top 10 categories or something.

**Comment by PanderMusubi** [comment]
The link is broken, please fix it. Thanks.

**Comment by bubelov** [comment]
Implemented in https://github.com/teambtcmap/btcmap-android/commit/90679350f63f76b0b97d203349929ef98553f003
