### ISSUE TITLE
Add social links to merchant pages.

### ISSUE THREAD

**Issue by dadofsambonzuki** [teambtcmap/btcmap-android#33]
Request from Bitcoin Island Philippines.

**Comment by bubelov** [comment]
What does it mean? We do display social links, where they're available. Taggers can use `contact:facebook`, `contact:twitter`, `contact:instagram` tags and so on

**Comment by dadofsambonzuki** [comment]
Do you show anything beginning contact:?

There are now many social tags.

**Comment by bubelov** [comment]
Yes, all the popular social links are supported, including the `contact` namespace
