### ISSUE TITLE
Can't install on pixel7 from fdroid

### ISSUE THREAD

**Issue by dkocich** [teambtcmap/btcmap-android#40]
There is a warning that system has blocked installation of a dangerous app

**Comment by bubelov** [comment]
Did the alert look like any of those?

![photo_5282723746341308380_y](https://github.com/teambtcmap/btcmap-android/assets/1189245/ea11b905-77f2-4220-af1b-d5b3589798b4)
![photo_5282723746341308379_y](https://github.com/teambtcmap/btcmap-android/assets/1189245/e19db9dc-be79-45ae-b82e-f600416f366e)

**Comment by dkocich** [comment]
[]()![Screenshot_20230709-102510.png](https://github.com/teambtcmap/btcmap-android/assets/6165660/45a96a13-4751-407a-9e63-a51e9d1d192d)

![Screenshot_20230709-102430.png](https://github.com/teambtcmap/btcmap-android/assets/6165660/86ca5897-14b0-40d0-8697-94585ec74fb0)

**Comment by bubelov** [comment]
Well, the F-Droid `apk` itself got this warning, I don't think we can do anything about it. It's just a dark pattern used by Google to scare off the users. BTC Map doesn't require any permissions and doesn't have any tracking. The Play Store version is tracked by Google but it looks like they're fine with that =)

Does the Play Store version work on your device? I just tried installing F-Droid version on my Pixel 6 and it works fine.

**Comment by dkocich** [comment]
it works on GPlay at least
