### ISSUE TITLE
translating instructions

### ISSUE THREAD

**Issue by jindam-vani** [teambtcmap/btcmap-android#43]
@bubelov please add how to add instructions about how to translate @ https://github.com/teambtcmap/btcmap-android#-help-with-translation

**Comment by bubelov** [comment]
@jindam-vani you can press the edit button to edit a text file which corresponds to your language:

![Screenshot from 2023-07-27 08-44-28](https://github.com/teambtcmap/btcmap-android/assets/1189245/ca5aaa3b-63a0-4186-a669-2d5873a2f032)
