### ISSUE TITLE
Bulgarian language support

### ISSUE THREAD

**Issue by GreoN5** [teambtcmap/btcmap-android#44]
Is there a possibility of adding Bulgarian language support, since I do not see it anywhere? I can help with translations of it. :)

**Comment by bubelov** [comment]
Sure, feel free to edit this file directly or via GH web editor: https://github.com/teambtcmap/btcmap-android/blob/master/app/src/main/res/values-bg/strings.xml

**Comment by GreoN5** [comment]
@bubelov Ready in a PR - https://github.com/teambtcmap/btcmap-android/pull/45
