### ISSUE TITLE
Search for zip codes (improvement)

### ISSUE THREAD

**Issue by serrq** [teambtcmap/btcmap-android#49]
The function seems to exist already but the results are not always exact. Sometimes they are mixed with other results that aren't consistent with the research carried out.

**Comment by bubelov** [comment]
If I understand it correctly, it depends on the availability of an [addr:postcode](https://wiki.openstreetmap.org/wiki/Key:addr:postcode) tag, which can be added by the local mappers. There is nothing we can do about missing zip codes, except for asking editors to add them to their local places
