### ISSUE TITLE
Shareable URL from Android

### ISSUE THREAD

**Issue by dadofsambonzuki** [teambtcmap/btcmap-android#53]
It would be great to be able to share the URL of the merchant from within the merchant page with friends via messaging apps or via social media.

This could be done through the standard Android share pane.

**Comment by bubelov** [comment]
Yea, we can either share a web app URL or launch a geo intent to open a native maps app, for cross-platform compat. I think our web browser link is a better option

**Comment by dadofsambonzuki** [comment]
Agree. Should be URL with native share pane.

Geo-intent better for navigating, which I see you just implemented. 🔥

**Comment by bubelov** [comment]
Done
