### ISSUE TITLE
Google Play Protect warning

### ISSUE THREAD

**Issue by juanjgit** [teambtcmap/btcmap-android#55]
When trying to upgrade to the latest version from F-Droid, the Google Play Protect service blocks the installation with a warning message (the message might not be accurate because I translated it from Spanish):

"Insecure application blocked. This application might gather data that can be used to track your activity. Installing this application might put your device in danger."

No other F-Droid application shows this message and I have several that use location, osm maps, etc.

**Comment by bubelov** [comment]
BTC Map can be used without a location permission, so it has nothing to do with security. I think it's just some Google BS, maybe it doesn't like Bitcoin being mentioned in a third-party app or something. The app does not require any permissions whatsoever.

You can download an identical build from Google Play and I bet they won't show you any warnings =)

**Comment by juanjgit** [comment]
You are right, no complains for the Google Play version. I also tried to install the apk from github release section got the same error.

![msg36316021-455186](https://github.com/teambtcmap/btcmap-android/assets/3613326/98f26b76-046c-431e-b73e-3572a654700b)
