### ISSUE TITLE
Fix crash on failing network calls during sync

### ISSUE THREAD

**Issue by AsmodeumX** [teambtcmap/btcmap-android#56]
App says it's fetching recent data and crashes

**Comment by bubelov** [comment]
Can you provide more details? Namely:

- app version
- store (play, fdrioid or github)
- android version

**Comment by asandikci** [comment]
Yes, v0.7.2 crashes. (v0.7.0 works)

**Comment by AsmodeumX** [comment]
> Can you provide more details? Namely:
> 
> - app version
> - store (play, fdroid or github)
> - android version

0.7.2
F-droid
10

**Comment by bubelov** [comment]
Okay, I experienced the same issue when the app did some network calls. It stopped crashing when my network connection improved

For some reason, network connection timeouts aren't always get caught silently, I'll look into that

**Comment by bubelov** [comment]
I think I fixed it in a preview release: https://github.com/teambtcmap/btcmap-android/releases/tag/preview

Will test it for a few days and publish, if those crashes are no more. You are welcome to use the preview build for now, if you are affected, but I don't think it should happen often, unless your network connection is extremely unreliable or our server is overloaded

**Comment by bubelov** [comment]
It's certainly fixed and it will be included in the next update on Friday
